# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3af9b8b2044843b9c2e4818668eecf7f0ab2e750788b4fb9c2530512f21e97d12741ce7706ce6915da6a3ecb22357950c7ec52e51891002638d6e96f89baec

test:
  secret_key_base: b313559415615d1bc63d8f7407362c67a351aa090d9b870cf5bd793229e5aba16b84a059a3918f1bd3410de794782f4ed092ba4d0ed555d2f14ddb204fd06310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
